import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    weight: ["400", "600", "500", "700"],
    style: "normal",
    subsets: ["latin"],
    variable: "--font-pop",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body className={`${poppins.variable}`}>{children}</body>
        </html>
    );
};
export default RootLayout;
